service: quickbooks-ai-agent

provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'prod'}
  memorySize: 1024
  timeout: 30
  
  environment:
    SAGEMAKER_ENDPOINT_NAME: ${env:SAGEMAKER_ENDPOINT_NAME, ''}
    RAG_SERVICE_URL: ${env:RAG_SERVICE_URL, ''}
    API_KEY: ${env:API_KEY, ''}
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sagemaker:InvokeEndpoint
      Resource: 
        - arn:aws:sagemaker:${self:provider.region}:*:endpoint/*
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:*:*:*

functions:
  api:
    handler: lambda_handler.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: ${env:CORS_ORIGIN, '*'}
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: /
          method: ANY
          cors:
            origin: ${env:CORS_ORIGIN, '*'}
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

package:
  exclude:
    - node_modules/**
    - .git/**
    - .pytest_cache/**
    - __pycache__/**
    - "*.pyc"
    - tests/**
